### ISSUE TITLE
The result is not like the original design.

### ISSUE THREAD

**Issue by artmarydotir** [fatemeh-ta/list#1]
1. The form is not aligned.

2. Class names should make sense,class names should not be like this:
**class2** , **class3** , **class4**
**The name of the class must indicate its content.**
instead of using class4 ---> use header-title.

3. Where is your container in css ?

![Screenshot from 2020-04-15 18-03-16](https://user-images.githubusercontent.com/11363931/79343355-89d20400-7f43-11ea-9123-059dd955939a.png)

*****

**Comment by fatemeh-ta** [comment]
Html file is changed
